version: '3.8'
services:
  nsp_backend:
    container_name: nsp_backend
    build:
      context: .  
    
    image: backend-glee
    #Container name
    #Port connection
    ports:                          
      - "5000:5000"
    environment:
     - EXTERNAL_PORT=5000
     - PGUSER=postgres
     - PGPASSWORD=Zelender384127
     - PGDATABASE=backend-glee
     - PGHOST=nsp_db
    depends_on:
     - nsp_db
    # tty: true
  nsp_db:
    container_name: nsp_db
    # container_name: n_database
    image: postgres:15-alpine
    ports:                          
      - "5432:5432"
    environment:
     - POSTGRES_DB=backend-glee
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=Zelender384127
    #  - POSTGRES_HOST_AUTH_METHOD = trust
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: {}