version: '3'
services:
  app:
    build:
      context: ./  
    depends_on:
      - database
    image: postgres:14.9
    #volumes setting
    volumes:
     - ":/app"
    #Container name
    container_name: n-app
    #Port connection
    ports:                          
      - "3000:5000"
    environment:
     - PORT: 5000
     - DB_NAME: backend-glee
     - DB_USER: postgres
     - DB_PASSWORD: Zelender384127
     - DB_HOST: db
     - DB_PORT: 5432
     - SECRET_KEY: secretik
    tty: true

  database:
    # container_name: n_database
    image: postgres:12.3
    ports:                          
      - "5432:5432"
    environment:
      POSTGRES_DB: backend-glee
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Zelender384127
      volumes:
      - nps_data:/var/lib/postgresql/data
volumes:
  nps_data: {}